version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@vue/cli"
    versions:
    - 4.5.10
    - 4.5.11
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.10
    - 4.5.11
